pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-project .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 80:80 devops-project'
            }
        }

    }
}
