pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/SayambarRanjeet/aws-devops-production-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-project ./app'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker tag devops-project sayambarranjeet/devops-project:latest'
                sh 'docker push sayambarranjeet/devops-project:latest'
            }
        }

        stage('Deploy Container') {
            steps {
                sh 'docker stop devops-project || true'
                sh 'docker rm devops-project || true'
                sh 'docker run -d -p 80:80 --name devops-project sayambarranjeet/devops-project:latest'
            }
        }

    }
}
